language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: XjDfhbug2+x1NWYFXvr2RpKTkrvAdsHBOzeGtp3eKMl0eJmjx3g9TmhH7aTDMKpH84jNjipo+b2ce7r42EHA6eptUVVC81DjmiiImCSkxe9DFn398p+QLbVsIfMRsjitYLx9QnSNuJk5+Ewhc15DyRhPz/0VeT/PYp/fTWeVbXo=
  - secure: krMikbCspZQEUHc7MgcFD+k55nkRRL7NT6TDpxNQoFunrfsFq8LNNfgcZ0udkFkwpRsUsveTRNLrlij2Mix0oJU0KioHEauD1NhT62dPI/gaOWV0yMPvtF6gyzTaNKkZXZxHMBfl0Uo1zL/zn3dKG+3CPBYbo0+4IOOI+LIwsns=
  - secure: rSh6XEJqZ2iQ7/Ls5FlDH44Ed5ZjaKmSoZ9SKU11MLKbbtwuCIK4RUcXa5jm6cpfsnba9eBjmRqRBaswhYAYEURTqWSqAPPylyRV69Ayor2G6G4LjjRh2x6+yWbLWBbW8tFZwWVXZvayBv1PYD0L8EZgQM7v1gYyUYIGCFzuZK4=
addons:
  ssh_known_hosts:
  - 128.199.54.7
script: ./node_modules/.bin/docpad generate --silent --env production
branches:
  only:
  - dev
after_success:
- sudo apt-get -y -qq install sshpass
- rsync -arlptzO --delete --stats --rsh="sshpass -p $DEPLOY_PASSWORD ssh -l $DEPLOY_USER" ./out/ 128.199.54.7:$DEPLOY_DEST
